language: php
sudo: false

php:
  - '7.1'

addons:
  sonarcloud:
    organization: "ooredroxoo-github"

git:
  depth: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner